### ISSUE TITLE
Other languages - use accent

### ISSUE THREAD

**Issue by DerMerz** [BrianJr03/Issa-AI-App#32]
A simple setting for output in german.

**Comment by BrianJr03** [comment]
If you append "and only respond in German" to your conversational context, ChatGPT will respond in German. I plan on updating the app to speak in the accent that correlates with your phone's default language.

**Comment by DerMerz** [comment]
That would be awesome

Best wishes,

________________________________

**Comment by DerMerz** [comment]
Thank you 😁

Best wishes,
Kevin Merz
________________________________
